In [12]:
import tensorflow as tf

# Loading dataset

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 1s 0us/step


# Defining the model

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.11966116, -0.5161615 , -0.82653034,  0.03288543, -0.3066728 ,
         0.4198735 ,  0.40867105,  0.7087205 ,  0.8356941 ,  0.75497633]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.08397041, 0.04446231, 0.03259872, 0.07699102, 0.05482414,
        0.11337227, 0.11210932, 0.15133923, 0.1718286 , 0.15850398]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

# fitting the model

In [8]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4787 - accuracy: 0.8607
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1467 - accuracy: 0.9561
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1061 - accuracy: 0.9682
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0905 - accuracy: 0.9719
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0742 - accuracy: 0.9765


# Model Evaluation

In [9]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0735 - accuracy: 0.9778


[0.07349873334169388, 0.9778000116348267]

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.2096595e-08, 1.7469487e-10, 2.4287244e-06, 5.5799272e-05,
        3.4740766e-10, 1.9532908e-06, 3.5478654e-13, 9.9993432e-01,
        3.8062772e-08, 5.5870919e-06],
       [8.8996012e-07, 2.2964319e-04, 9.9963927e-01, 1.0191093e-04,
        5.9032064e-14, 2.6188723e-05, 1.2985287e-06, 2.3295123e-15,
        8.8686426e-07, 2.2922617e-13],
       [3.7515946e-07, 9.9743879e-01, 4.2733524e-04, 1.8089851e-05,
        1.2389173e-04, 9.6222160e-05, 2.4664900e-05, 1.3229304e-03,
        5.4556085e-04, 2.2278045e-06],
       [9.9978918e-01, 2.7496963e-08, 2.0699945e-05, 1.9912040e-06,
        4.3555505e-07, 2.3324201e-06, 5.0848270e-05, 1.0361261e-04,
        1.1670278e-07, 3.0806230e-05],
       [2.6365897e-05, 1.3111850e-07, 5.1264669e-05, 1.4399129e-06,
        9.8964536e-01, 1.0082864e-05, 1.3495464e-05, 4.7678044e-05,
        5.1958095e-06, 1.0199073e-02]], dtype=float32)>